import type { Lang } from "./i18n";

export interface ProjectT { subtitle: string; description: string; highlights: string[] }

type PMap = Record<string, ProjectT>;

const EN: PMap = {
  "01": { subtitle: "Multi-Agent System", description: "Distributed army of 4 autonomous Claude Code agents. Telegram-controlled. Three modes: Autopilot / Supervised / Manual. Each agent has memory, tools, and role isolation.", highlights: ["4 AI agents with unique specializations", "Automatic task decomposition & delegation", "Three modes: Autopilot, Supervised, Manual", "Real-time Dashboard in Telegram"] },
  "02": { subtitle: "Voice AI for Business", description: "Voice robot for beauty salon. Full AI-driven phone dialogues — booking, rescheduling, reminders. Handles objections, understands context across turns.", highlights: ["Natural voice dialogues", "CRM integration", "Automated reminders & confirmations", "Multi-scenario: booking, reschedule, confirm"] },
  "03": { subtitle: "AI Task Assistant", description: "Telegram bot converting raw ideas (text/voice) into structured Todoist tasks. AI prioritization and agent routing.", highlights: ["Voice input via Whisper STT", "AI task structuring & routing", "Auto-prioritization", "Todoist integration"] },
  "04": { subtitle: "Full AI Administrator", description: "Complete AI administrator for beauty salon. LLM-driven dialogue without templates. Schedule management. Autonomous 24/7.", highlights: ["Template-free LLM dialogues", "Schedule management", "Telegram calls integration", "Autonomous 24/7 operation"] },
  "05": { subtitle: "RAG Knowledge Base", description: "Enterprise knowledge base: upload PDF, DOCX, URLs, Notion — get AI assistant that answers with inline source citations.", highlights: ["Supports PDF, DOCX, URL, Notion", "Semantic search across documents", "Answers with inline citations", "Ready widget for site / Telegram"] },
  "06": { subtitle: "Lead Qualification Bot", description: "WhatsApp/Telegram lead qualification using BANT methodology. Scores 1–10, auto-syncs hot leads to CRM with full conversation context.", highlights: ["Intelligent BANT qualification", "Lead scoring 1–10 scale", "Auto-push to HubSpot / Bitrix", "Hot lead alerts to manager"] },
  "07": { subtitle: "AI Customer Support", description: "First-line support agent trained on historical tickets. Handles 10+ languages. Escalates complex cases to humans with full context.", highlights: ["Trained on historical tickets & FAQ", "Smart escalation with context", "10+ languages supported", "Zendesk / Intercom / Freshdesk"] },
  "08": { subtitle: "AI Content Automation", description: "N8N pipeline: one idea → 10 posts adapted for Instagram, LinkedIn, Telegram, Twitter in the right brand tone and format.", highlights: ["Brief → ready posts in minutes", "Adapts tone per platform", "Auto-scheduling via Buffer", "Monthly content plan in 5 min"] },
  "09": { subtitle: "Property Assistant Bot", description: "AI agent for real estate. Matches properties by parameters, answers questions 24/7, books viewings in Google Calendar, updates CRM.", highlights: ["Smart matching by parameters", "24/7 Q&A about listings", "Viewing booking in Calendar", "CRM updates & agent alerts"] },
  "10": { subtitle: "AI Email Automation", description: "AI email processing: classifies inbound, prioritizes, drafts replies in 3 seconds, auto-sends standard responses, escalates edge cases.", highlights: ["Auto-classification of inbound", "Draft reply in 3 seconds", "Auto-sends FAQ responses", "Smart escalation of edge cases"] },
  "11": { subtitle: "AI Legal Review", description: "Upload any contract — get risk analysis, red flags, clause comparison against templates, and plain-language summary in 30 seconds.", highlights: ["Risk & red flag analysis in 30s", "Compare against template standards", "Highlights dangerous clauses", "Plain-language summary"] },
  "12": { subtitle: "AI Recruitment Agent", description: "Multi-agent recruitment pipeline: screens 100+ resumes, conducts async chat interviews, AI-scores candidates, books finals automatically.", highlights: ["Screen 100+ resumes in minutes", "Async interview via Telegram/Web", "AI scoring by custom criteria", "Auto-booking of final interviews"] },
  "13": { subtitle: "Business Intelligence Agent", description: "AI monitors revenue, CAC, LTV and conversion — auto-diagnoses anomalies and sends Telegram alerts with root cause analysis.", highlights: ["Connects to DB / Sheets / Metabase", "Daily AI metric digest", "Alert on anomaly detection", "Root cause AI diagnosis"] },
  "14": { subtitle: "Autonomous Code Review Agent", description: "Autonomous code review agent. Analyzes PRs for bugs, security vulns, performance issues. Writes inline comments. Learns team conventions.", highlights: ["PR analysis < 60 seconds", "OWASP security checks", "Learns team coding style", "Inline comments like a human"] },
  "16": { subtitle: "AI Meeting Assistant", description: "Records meetings via bot, transcribes, extracts action items, assigns owners, pushes tasks to project management tools automatically.", highlights: ["Live meeting transcription", "Action item extraction", "Auto-assign to owners", "Push to Notion / Todoist"] },
  "17": { subtitle: "Regulatory Compliance AI", description: "Regulatory compliance checker. Upload policies + new docs — AI flags violations, suggests fixes, tracks compliance score over time.", highlights: ["Multi-regulation checking", "Compliance scoring with history", "Fix suggestions per violation", "Full audit trail"] },
  "18": { subtitle: "Universal Client Manager", description: "AI admin for any service professional. Handles bookings, client management, auto-marketing \u2014 all from Telegram. Lite version of Svetlana AI-admin.", highlights: ["Smart booking & scheduling", "Client CRM with history", "Auto-marketing & promotions", "Multi-channel communication"] },
  "19": { subtitle: "Instagram AI Auto-Responder", description: "AI auto-replies to every Instagram comment on your posts and reels. Sounds like you. Works 24/7. Boosts engagement by up to 3x. Buy once — your reels machine forever.", highlights: ["Instant AI replies to every comment", "Custom brand voice & tone settings", "Smart spam filtering & VIP escalation", "Analytics dashboard with sentiment tracking"] },
};

const RU: PMap = {
  "01": { subtitle: "Мультиагентная система", description: "Распределённая армия из 4 автономных Claude Code агентов. Управление через Telegram. Три режима: Автопилот / Супервизор / Ручной. Каждый агент — своя память, инструменты, изоляция ролей.", highlights: ["4 AI-агента с уникальными специализациями", "Автоматическая декомпозиция и делегирование задач", "Три режима: Автопилот, Супервизор, Ручной", "Dashboard в реальном времени в Telegram"] },
  "02": { subtitle: "Голосовой AI для бизнеса", description: "Голосовой робот для салона красоты. Полностью AI-управляемые телефонные диалоги — запись, перенос, напоминания. Обрабатывает возражения, понимает контекст разговора.", highlights: ["Естественные голосовые диалоги", "Интеграция с CRM", "Автоматические напоминания и подтверждения", "Мульти-сценарий: запись, перенос, подтверждение"] },
  "03": { subtitle: "AI-ассистент задач", description: "Telegram-бот, превращающий сырые идеи (текст/голос) в структурированные задачи Todoist. AI-приоритизация и маршрутизация по агентам.", highlights: ["Голосовой ввод через Whisper STT", "AI-структурирование и маршрутизация задач", "Автоприоритизация", "Интеграция с Todoist"] },
  "04": { subtitle: "Полный AI-администратор", description: "Полноценный AI-администратор для салона красоты. LLM-диалоги без шаблонов. Управление расписанием. Автономная работа 24/7.", highlights: ["Диалоги на LLM без шаблонов", "Управление расписанием", "Интеграция звонков через Telegram", "Автономная работа 24/7"] },
  "05": { subtitle: "RAG база знаний", description: "Корпоративная база знаний: загрузите PDF, DOCX, URL, Notion — получите AI-ассистента, который отвечает с цитированием источников.", highlights: ["Поддержка PDF, DOCX, URL, Notion", "Семантический поиск по документам", "Ответы с цитированием источников", "Готовый виджет для сайта / Telegram"] },
  "06": { subtitle: "Бот квалификации лидов", description: "Квалификация лидов в WhatsApp/Telegram по методологии BANT. Оценка 1–10, автосинхронизация горячих лидов в CRM с полным контекстом.", highlights: ["Интеллектуальная BANT-квалификация", "Скоринг лидов по шкале 1–10", "Автопуш в HubSpot / Bitrix", "Алерты менеджеру о горячих лидах"] },
  "07": { subtitle: "AI-поддержка клиентов", description: "Агент первой линии, обученный на исторических тикетах. Работает на 10+ языках. Эскалирует сложные кейсы людям с полным контекстом.", highlights: ["Обучен на исторических тикетах и FAQ", "Умная эскалация с контекстом", "Поддержка 10+ языков", "Zendesk / Intercom / Freshdesk"] },
  "08": { subtitle: "AI-автоматизация контента", description: "N8N пайплайн: одна идея → 10 постов, адаптированных для Instagram, LinkedIn, Telegram, Twitter в нужном тоне бренда.", highlights: ["Бриф → готовые посты за минуты", "Адаптация тона под платформу", "Автопостинг через Buffer", "Контент-план на месяц за 5 минут"] },
  "09": { subtitle: "AI-ассистент недвижимости", description: "AI-агент для недвижимости. Подбирает объекты по параметрам, отвечает 24/7, записывает на просмотры в Google Calendar, обновляет CRM.", highlights: ["Умный подбор по параметрам", "Ответы на вопросы 24/7", "Запись на просмотр в Calendar", "Обновления CRM и алерты агенту"] },
  "10": { subtitle: "AI-автоматизация почты", description: "AI-обработка email: классифицирует входящие, приоритизирует, составляет ответы за 3 секунды, автоотправляет стандартные ответы, эскалирует спорные кейсы.", highlights: ["Автоклассификация входящих", "Черновик ответа за 3 секунды", "Автоотправка FAQ-ответов", "Умная эскалация спорных кейсов"] },
  "11": { subtitle: "AI-анализ договоров", description: "Загрузите любой договор — получите анализ рисков, красные флаги, сравнение с шаблонами и изложение простым языком за 30 секунд.", highlights: ["Анализ рисков и красных флагов за 30с", "Сравнение со стандартными шаблонами", "Выделение опасных пунктов", "Изложение простым языком"] },
  "12": { subtitle: "AI-рекрутинг агент", description: "Мультиагентный рекрутинг-пайплайн: скринит 100+ резюме, проводит async-интервью в чате, AI-скоринг кандидатов, автобронирование финалов.", highlights: ["Скрининг 100+ резюме за минуты", "Async-интервью через Telegram/Web", "AI-скоринг по кастомным критериям", "Автобронирование финальных интервью"] },
  "13": { subtitle: "AI-аналитика бизнеса", description: "AI мониторит выручку, CAC, LTV и конверсию — автоматически диагностирует аномалии и отправляет алерты в Telegram с анализом причин.", highlights: ["Подключение к БД / Sheets / Metabase", "Ежедневный AI-дайджест метрик", "Алерт при обнаружении аномалий", "AI-диагностика причин"] },
  "14": { subtitle: "Автономный агент code review", description: "Автономный агент ревью кода. Анализирует PR на баги, уязвимости, проблемы производительности. Пишет inline-комментарии. Учится конвенциям команды.", highlights: ["Анализ PR < 60 секунд", "Проверки безопасности OWASP", "Изучает стиль кода команды", "Inline-комментарии как у человека"] },
  "16": { subtitle: "AI-ассистент встреч", description: "Записывает встречи через бота, транскрибирует, извлекает action items, назначает ответственных, пушит задачи в инструменты управления проектами.", highlights: ["Транскрипция встреч в реальном времени", "Извлечение action items", "Автоназначение ответственных", "Пуш в Notion / Todoist"] },
  "17": { subtitle: "AI-комплаенс и регуляторика", description: "Проверка регуляторного комплаенса. Загрузите политики + новые документы — AI выявляет нарушения, предлагает исправления, отслеживает скор.", highlights: ["Мультирегуляторные проверки", "Комплаенс-скоринг с историей", "Рекомендации по каждому нарушению", "Полный audit trail"] },
  "18": { subtitle: "Универсальный клиент-менеджер", description: "AI-админ для любого специалиста. Запись, клиенты, маркетинг — всё через Telegram. Лайт-версия Svetlana AI-admin.", highlights: ["Умная запись и расписание", "CRM клиентов с историей", "Автомаркетинг и акции", "Мультиканальная коммуникация"] },
  "19": { subtitle: "AI авто-ответчик Instagram", description: "AI автоматически отвечает на каждый комментарий к вашим постам и Reels. Звучит как вы. Работает 24/7. Увеличивает вовлечённость до 3x. Купи один раз — ваша машина Reels навсегда.", highlights: ["Мгновенные AI-ответы на каждый комментарий", "Настройка голоса и стиля бренда", "Умная фильтрация спама и VIP-эскалация", "Аналитический дашборд с трекингом тональности"] },
};

const UA: PMap = {
  "01": { subtitle: "Мультиагентна система", description: "Розподілена армія з 4 автономних Claude Code агентів. Керування через Telegram. Три режими: Автопілот / Супервізор / Ручний. Кожен агент — власна пам'ять, інструменти, ізоляція ролей.", highlights: ["4 AI-агенти з унікальними спеціалізаціями", "Автоматична декомпозиція та делегування задач", "Три режими: Автопілот, Супервізор, Ручний", "Dashboard в реальному часі в Telegram"] },
  "02": { subtitle: "Голосовий AI для бізнесу", description: "Голосовий робот для салону краси. Повністю AI-керовані телефонні діалоги — запис, перенесення, нагадування. Обробляє заперечення, розуміє контекст розмови.", highlights: ["Природні голосові діалоги", "Інтеграція з CRM", "Автоматичні нагадування та підтвердження", "Мульти-сценарій: запис, перенесення, підтвердження"] },
  "03": { subtitle: "AI-асистент задач", description: "Telegram-бот, що перетворює сирі ідеї (текст/голос) на структуровані задачі Todoist. AI-пріоритизація та маршрутизація по агентах.", highlights: ["Голосовий ввід через Whisper STT", "AI-структурування та маршрутизація задач", "Автопріоритизація", "Інтеграція з Todoist"] },
  "04": { subtitle: "Повний AI-адміністратор", description: "Повноцінний AI-адміністратор для салону краси. LLM-діалоги без шаблонів. Керування розкладом. Автономна робота 24/7.", highlights: ["Діалоги на LLM без шаблонів", "Керування розкладом", "Інтеграція дзвінків через Telegram", "Автономна робота 24/7"] },
  "05": { subtitle: "RAG база знань", description: "Корпоративна база знань: завантажте PDF, DOCX, URL, Notion — отримайте AI-асистента, який відповідає з цитуванням джерел.", highlights: ["Підтримка PDF, DOCX, URL, Notion", "Семантичний пошук по документах", "Відповіді з цитуванням джерел", "Готовий віджет для сайту / Telegram"] },
  "06": { subtitle: "Бот кваліфікації лідів", description: "Кваліфікація лідів у WhatsApp/Telegram за методологією BANT. Оцінка 1–10, автосинхронізація гарячих лідів у CRM з повним контекстом.", highlights: ["Інтелектуальна BANT-кваліфікація", "Скоринг лідів за шкалою 1–10", "Автопуш до HubSpot / Bitrix", "Алерти менеджеру про гарячих лідів"] },
  "07": { subtitle: "AI-підтримка клієнтів", description: "Агент першої лінії, навчений на історичних тікетах. Працює на 10+ мовах. Ескалює складні кейси людям з повним контекстом.", highlights: ["Навчений на історичних тікетах та FAQ", "Розумна ескалація з контекстом", "Підтримка 10+ мов", "Zendesk / Intercom / Freshdesk"] },
  "08": { subtitle: "AI-автоматизація контенту", description: "N8N пайплайн: одна ідея → 10 постів, адаптованих для Instagram, LinkedIn, Telegram, Twitter у потрібному тоні бренду.", highlights: ["Бриф → готові пости за хвилини", "Адаптація тону під платформу", "Автопостинг через Buffer", "Контент-план на місяць за 5 хвилин"] },
  "09": { subtitle: "AI-асистент нерухомості", description: "AI-агент для нерухомості. Підбирає об'єкти за параметрами, відповідає 24/7, записує на перегляди в Google Calendar, оновлює CRM.", highlights: ["Розумний підбір за параметрами", "Відповіді на запитання 24/7", "Запис на перегляд у Calendar", "Оновлення CRM та алерти агенту"] },
  "10": { subtitle: "AI-автоматизація пошти", description: "AI-обробка email: класифікує вхідні, пріоритизує, складає відповіді за 3 секунди, автовідправляє стандартні відповіді, ескалює спірні кейси.", highlights: ["Автокласифікація вхідних", "Чернетка відповіді за 3 секунди", "Автовідправка FAQ-відповідей", "Розумна ескалація спірних кейсів"] },
  "11": { subtitle: "AI-аналіз договорів", description: "Завантажте будь-який договір — отримайте аналіз ризиків, червоні прапорці, порівняння з шаблонами та виклад простою мовою за 30 секунд.", highlights: ["Аналіз ризиків та червоних прапорців за 30с", "Порівняння зі стандартними шаблонами", "Виділення небезпечних пунктів", "Виклад простою мовою"] },
  "12": { subtitle: "AI-рекрутинг агент", description: "Мультиагентний рекрутинг-пайплайн: скринить 100+ резюме, проводить async-інтерв'ю в чаті, AI-скоринг кандидатів, автобронювання фіналів.", highlights: ["Скринінг 100+ резюме за хвилини", "Async-інтерв'ю через Telegram/Web", "AI-скоринг за кастомними критеріями", "Автобронювання фінальних інтерв'ю"] },
  "13": { subtitle: "AI-аналітика бізнесу", description: "AI моніторить виручку, CAC, LTV та конверсію — автоматично діагностує аномалії та відправляє алерти в Telegram з аналізом причин.", highlights: ["Підключення до БД / Sheets / Metabase", "Щоденний AI-дайджест метрик", "Алерт при виявленні аномалій", "AI-діагностика причин"] },
  "14": { subtitle: "Автономний агент code review", description: "Автономний агент ревью коду. Аналізує PR на баги, вразливості, проблеми продуктивності. Пише inline-коментарі. Вивчає конвенції команди.", highlights: ["Аналіз PR < 60 секунд", "Перевірки безпеки OWASP", "Вивчає стиль коду команди", "Inline-коментарі як у людини"] },
  "16": { subtitle: "AI-асистент зустрічей", description: "Записує зустрічі через бота, транскрибує, витягує action items, призначає відповідальних, пушить задачі в інструменти управління проєктами.", highlights: ["Транскрипція зустрічей в реальному часі", "Витягування action items", "Автопризначення відповідальних", "Пуш в Notion / Todoist"] },
  "17": { subtitle: "AI-комплаєнс та регуляторика", description: "Перевірка регуляторного комплаєнсу. Завантажте політики + нові документи — AI виявляє порушення, пропонує виправлення, відстежує скор.", highlights: ["Мультирегуляторні перевірки", "Комплаєнс-скоринг з історією", "Рекомендації по кожному порушенню", "Повний audit trail"] },
  "18": { subtitle: "Універсальний клієнт-менеджер", description: "AI-адмін для будь-якого спеціаліста. Запис, клієнти, маркетинг — все через Telegram.", highlights: ["Розумний запис та розклад", "CRM клієнтів з історією", "Автомаркетинг та акції", "Мультиканальна комунікація"] },
  "19": { subtitle: "AI авто-відповідач Instagram", description: "AI автоматично відповідає на кожен коментар до ваших постів та Reels. Звучить як ви. Працює 24/7. Збільшує залученість до 3x. Купіть один раз — ваша машина Reels назавжди.", highlights: ["Миттєві AI-відповіді на кожен коментар", "Налаштування голосу та стилю бренду", "Розумна фільтрація спаму та VIP-ескалація", "Аналітичний дашборд з трекінгом тональності"] },
};

export const projectI18n: Record<Lang, PMap> = { EN, RU, UA };
